global:
  seleniumGrid:
    autoscaling:
      useKEDA: true
      enabled: true
    graphqlUrl: "http://selenium-router:4444/graphql"

scale-chrome-node:
  enabled: true
  minReplicaCount: 0
  maxReplicaCount: 20
  scaleTargetRef:
    name: selenium-chrome-node
  triggers: []

scale-firefox-node:
  enabled: true
  minReplicaCount: 0
  maxReplicaCount: 20
  scaleTargetRef:
    name: selenium-firefox-node
  triggers: []

scale-edge-node:
  enabled: true
  minReplicaCount: 0
  maxReplicaCount: 20
  scaleTargetRef:
    name: selenium-edge-node
  triggers: []
