apiVersion: v2
name: scalable-selenium-grid
description: A Helm chart for Kubernetes
type: application
version: 23.4.0
appVersion: "23.4.0"
dependencies:
  - condition: global.selenium-grid.enabled, selenium-grid.enabled
    name: selenium-grid
    repository: https://www.selenium.dev/docker-selenium
    version: 0.15.7
    tags:
      - full
      - selenium-grid
  - condition: global.jaeger-all-in-one.enabled, jaeger-all-in-one.enabled
    name: jaeger-all-in-one
    repository: https://raw.githubusercontent.com/hansehe/jaeger-all-in-one/master/helm/charts
    version: 0.1.8
    tags:
      - full
      - jaeger-all-in-one
  - condition: global.ingress-nginx.enabled, ingress-nginx.enabled
    name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.0.6
    tags:
      - full
      - ingress-nginx