global:
  seleniumGrid:
    persistence:
      enabled: true

persistence:
  pv:
    enabled: true
    hostPath:
      path: "-"
    #storageClass: "-"
  enabled: true
  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  #storageClass: "-"
  ## Persistent Volume Claim annotations
  ##
  annotations:
  ## Persistent Volume Access Mode
  ##
  accessModes: ReadWriteMany
  ## Persistent Volume size
  ##
  size: 2Gi