apiVersion: v1
kind: ConfigMap
metadata:
  name: selenium-configurations
  labels:
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "configurations/Video/*").AsConfig | indent 2 }}