apiVersion: v2
name: grid-pvc
description: A Helm chart for Kubernetes
type: application
version: 23.4.0
appVersion: "23.4.0"
dependencies:
  - alias: selenium-chrome-node
    condition: global.persistence.enabled,selenium-chrome-node.enabled
    name: component-pvc
    repository: file://../../../../../component-pvc/src/main/resources/component-pvc
    version: 23.4.0
  - alias: selenium-chrome-video
    condition: global.persistence.enabled,selenium-chrome-video.enabled
    name: component-pvc
    repository: file://../../../../../component-pvc/src/main/resources/component-pvc
    version: 23.4.0