{{- if .Values.global.seleniumGrid.autoscaling.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grid-secret
  namespace: {{ .Release.Namespace }}
  labels:
    component: grid-secret
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  graphql-url: {{ .Values.global.seleniumGrid.graphqlUrl | b64enc }}
{{- end }}