{{- if and (or .Values.persistence.enabled .Values.global.seleniumGrid.persistence.enabled) (or .Values.nameOverride .Values.persistence.enabled) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "component-pvc.name" . }}-pvc
  labels:
    app: {{ template "component-pvc.name" . }}
    chart: {{ template "component-pvc.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | quote }}
  resources:
    requests:
  {{- if not .Values.persistence.size }}
      storage: 100Mi
  {{- else }}
      storage: {{ .Values.persistence.size | quote }}
  {{- end }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}

