tags:
  full: true
  selenium-grid: false
  jaeger-all-in-one: false
  ingress-nginx: false
  keda: false
  webdav: false

global:
  seleniumGrid:
    persistence:
      enabled: &persistence false
    autoscaling:
      enableWithExistingKEDA: &enableWithExistingKEDA true
    tracing:
      enabled: false
      jaegerEndpoint: http://{{ .Release.Name }}-jaeger-all-in-one-headless:14250
  selenium-grid:
    #enabled: true
  jaeger-all-in-one:
    #enabled: true
  ingress-nginx:
    #enabled: true
  keda:
    #enabled: true

grid-pvc:
  selenium-node: #claimName to be used by selenium-grid.node.extraVolumes
    persistence:
      enabled: *persistence
      size: 15Gi
      pv:
        enabled: *persistence
        hostPath:
          path: /testops/local/selenium

selenium-grid:
  #enabled: true
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/app-root: &gridAppRoot "/selenium"
    ingressClassName: nginx
    hostname: "aws.ndviet.org"
    paths:
      - path: /selenium(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ template "seleniumGrid.router.fullname" $ }}'
            port:
              number: 4444
  basicAuth:
    enabled: false
  isolateComponents: true
  autoscaling:
    enableWithExistingKEDA: *enableWithExistingKEDA
    scalingType: job
    annotations:
      helm.sh/hook: post-install,post-upgrade,post-rollback
    scaledOptions:
      minReplicaCount: 0
      maxReplicaCount: 8
      pollingInterval: 15
    scaledJobOptions:
      successfulJobsHistoryLimit: 0 # clean up pods with status Completed
      failedJobsHistoryLimit: 5
      scalingStrategy:
        strategy: default
    deregisterLifecycle:
      preStop:
        exec:
          command:
            - bash
            - -c
            - |
              curl -X POST 127.0.0.1:5555/se/grid/node/drain --header 'X-REGISTRATION-SECRET;' && \
              curl -X POST 127.0.0.1:9000/drain --header 'X-REGISTRATION-SECRET;' && \
              while curl 127.0.0.1:5555/status; do sleep 1; done;
  hub:
    subPath: *gridAppRoot
    extraEnvironmentVariables:
  components:
    subPath: *gridAppRoot
    extraEnvironmentVariables:
    extraEnvFrom: &extraEnvFrom
      - configMapRef:
          name: selenium-tracing-config

  chromeNode:
    resources: &resources
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1Gi"
        cpu: "1"
    extraEnvFrom: *extraEnvFrom
    extraEnvironmentVariables: &extraEnvironmentVariablesNodes
      - name: SE_NODE_GRID_URL
        value: http://aws.ndviet.org/selenium
#      - name: SE_NODE_SESSION_TIMEOUT
#        value: "300"
#      - name: SE_NODE_OVERRIDE_MAX_SESSIONS
#        value: "true"
      - name: DRAIN_AFTER_SESSION_COUNT #must add this to drain video together with session
        value: "1"
      - name: SE_NODE_MAX_SESSIONS #ensure the mapping is 1 session - 1 recording
        value: "1"
      - name: SE_VIDEO_RECORD #must add this to enable video recording
        value: "true"
      - name: SE_VNC_NO_PASSWORD
        value: "true"
      - name: SE_NODE_PORT
        value: "5555"
      - name: SE_VIDEO_FOLDER
        value: &SE_VIDEO_FOLDER "/videos"
      - name: SE_SESSION_FOLDER
        value: &SE_SESSION_FOLDER "/sessions"
      - name: SE_OPTS
        value: "--enable-managed-downloads true"
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: DISPLAY_CONTAINER_NAME
        value: $(POD_IP)
      - name: SE_DOWNLOAD_MOUNT_PATH
        value: data/$(POD_NAME)
    ports: &nodePorts
      - 5555
    extraVolumeMounts:
#      - name: node-data
#        mountPath: /home/seluser/Downloads
#        subPathExpr: $(SE_DOWNLOAD_MOUNT_PATH)
#      - name: node-data
#        mountPath: *SE_SESSION_FOLDER
#        subPath: data
    extraVolumes: &nodeVolumes
#      - name: node-data
#        persistentVolumeClaim:
#          claimName: &seleniumClaim "selenium-node"
    startupProbe: &nodeStartupProbe
      httpGet:
        path: /status
        port: 5555
      failureThreshold: 120
      periodSeconds: 1

  firefoxNode:
    resources: *resources
    extraEnvFrom: *extraEnvFrom
    extraEnvironmentVariables: *extraEnvironmentVariablesNodes
    ports: *nodePorts
    extraVolumes: *nodeVolumes
    startupProbe: *nodeStartupProbe

  edgeNode:
    resources: *resources
    extraEnvFrom: *extraEnvFrom
    extraEnvironmentVariables: *extraEnvironmentVariablesNodes
    ports: *nodePorts
    extraVolumes: *nodeVolumes
    startupProbe: *nodeStartupProbe

  videoRecorder:
    enabled: false
    uploadDestinationPrefix: false
    uploader: false
    extraEnvironmentVariables: *extraEnvironmentVariablesNodes
    volume:
      name:
        videoFolder: "videos"
        videoScripts: "configurations"
    extraVolumeMounts:
#      - name: configurations
#        mountPath: /opt/bin/video.sh
#        subPath: video.sh
#      - name: node-data
#        mountPath: *SE_VIDEO_FOLDER
#        subPath: videos
#      - name: configurations
#        mountPath: /opt/bin/session_task.sh
#        subPath: session_task.sh
#      - name: configurations
#        mountPath: /etc/supervisord.conf
#        subPath: supervisord.conf
#      - name: configurations
#        mountPath: /opt/bin/video_ready.py
#        subPath: video_ready.py
    extraVolumes:
#      - name: configurations
#        configMap:
#          name: "selenium-configurations"
#          defaultMode: 0511

jaeger-all-in-one:
  enabled: false

keda:
  #enabled: true
  webhooks:
    enabled: false
  http:
    timeout: 15000

webdav:
  #enabled: true
  persistence:
    enabled: *persistence
#    existingClaim: *seleniumClaim

ingress-nginx:
  #enabled: true
#  controller:
#    admissionWebhooks:
#      enabled: false
#    hostNetwork: true
#    kind: DaemonSet
#    service:
#      type: ClusterIP
  tcp:
    4444: "{{ .Release.Namespace }}/selenium-router:4444"
    16686: "{{ .Release.Namespace }}/{{ .Release.Name }}-jaeger-all-in-one-headless:16686"
    8080: "{{ .Release.Namespace }}/{{ .Release.Name }}-webdav:8080"
