apiVersion: v2
name: scalable-selenium-grid
description: A Helm umbrella chart for creating ecosystem of Autoscaling Selenium Grid in Kubernetes
type: application
version: ${chart.this.version}
appVersion: "${chart.this.version}"
icon: "${chart.this.icon}"
dependencies:
  - condition: global.selenium-grid.enabled, selenium-grid.enabled
    name: ${chart.selenium.name}
    repository: file://../../../../patch-selenium-grid/target/classes/patch-selenium-grid/charts/selenium-grid
    version: ${chart.selenium.version}
    tags:
      - full
      - selenium-grid

  - condition: global.seleniumGrid.autoscaling.enableWithExistingKEDA, global.keda.enabled, keda.enabled
    name: ${chart.keda.name}
    repository: ${chart.keda.repository}
    version: ${chart.keda.version}
    tags:
      - full
      - keda

  - condition: global.seleniumGrid.autoscaling.enableWithExistingKEDA, global.grid-autoscaling.enabled, grid-autoscaling.enabled
    name: grid-autoscaling
    repository: file://../../../../grid-autoscaling/target/classes/grid-autoscaling
    version: ${chart.this.version}
    tags:
      - full
      - keda

  - condition: global.seleniumGrid.persistence.enabled, global.grid-pvc.enabled, grid-pvc.enabled
    name: grid-pvc
    repository: file://../../../../grid-pvc/target/classes/grid-pvc
    version: ${chart.this.version}
    tags:
      - full
      - grid-pvc

  - condition: global.jaeger-all-in-one.enabled, jaeger-all-in-one.enabled
    name: ${chart.jaeger.name}
    repository: ${chart.jaeger.repository}
    version: ${chart.jaeger.version}
    tags:
      - full
      - jaeger-all-in-one

  - condition: global.ingress-nginx.enabled, ingress-nginx.enabled
    name: ${chart.ingress.name}
    repository: ${chart.ingress.repository}
    version: ${chart.ingress.version}
    tags:
      - full
      - ingress-nginx

  - condition: global.webdav.enabled, webdav.enabled
    name: ${chart.webdav.name}
    repository: ${chart.webdav.repository}
    version: ${chart.webdav.version}
    tags:
      - full
      - webdav