tags:
  full: true
  selenium-grid: false
  ingress-nginx: false
  keda: false

global:
  seleniumGrid:
    persistence:
      enabled: true
    autoscaling:
      #useKEDA: true
      enabled: true
    graphqlUrl: "http://selenium-router:4444/graphql"
    # Image tag for browser's recording
    videoImageTag: ffmpeg-4.3.1-20230404
  selenium-grid:
    #enabled: true
  jaeger-all-in-one:
    #enabled: true
  ingress-nginx:
    #enabled: true
  keda:
    #enabled: true

selenium-grid:
  #enabled: true
  isolateComponents: true
  components:
    extraEnvironmentVariables:
      - name: SE_NODE_MAX_SESSIONS
        value: "1"
      - name: SE_DRAIN_AFTER_SESSION_COUNT
        value: "1"
      - name: SE_ENABLE_TRACING
        value: "true"
      - name: JAVA_OPTS
        value: "-Dotel.traces.exporter=jaeger -Dotel.exporter.jaeger.endpoint=http://{{ .Release.Name }}-jaeger-all-in-one-headless:14250 -Dotel.resource.attributes=service.name=selenium"
  chromeNode:
    video:
      enabled: true
      imageName: selenium/video
      extraEnvironmentVariables: &videoExtraEnvVariables
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISPLAY_CONTAINER_NAME
          value: 0.0.0.0
        - name: FILE_NAME
          value: $(POD_NAME).mp4
      extraVolumeMounts: &videoExtraVolumeMounts
        - mountPath: /videos
          name: video-data-pvclaim
          subPathExpr: $(POD_NAME)
      extraVolumes:
        - name: video-data-pvclaim
          persistentVolumeClaim:
            claimName: selenium-chrome-video-data-pvclaim
    startupProbe:
      httpGet:
        path: /status
        port: 5555
      failureThreshold: 120
      periodSeconds: 2
    terminationGracePeriodSeconds: 3600
    lifecycle:
      preStop:
        exec:
          command:
            - bash
            - -c
            - |
              curl -X POST 127.0.0.1:5555/se/grid/node/drain --header 'X-REGISTRATION-SECRET;' && \
              while curl 127.0.0.1:5555/status; do sleep 1; done
  firefoxNode:
    video:
      enabled: true
      imageName: selenium/video
      extraEnvironmentVariables: *videoExtraEnvVariables
      extraVolumeMounts: *videoExtraVolumeMounts
      extraVolumes:
        - name: video-data-pvclaim
          persistentVolumeClaim:
            claimName: selenium-firefox-video-data-pvclaim
    startupProbe:
      httpGet:
        path: /status
        port: 5555
      failureThreshold: 120
      periodSeconds: 2
    terminationGracePeriodSeconds: 3600
    lifecycle:
      preStop:
        exec:
          command:
            - bash
            - -c
            - |
              curl -X POST 127.0.0.1:5555/se/grid/node/drain --header 'X-REGISTRATION-SECRET;' && \
              while curl 127.0.0.1:5555/status; do sleep 1; done
  edgeNode:
    video:
      enabled: true
      imageName: selenium/video
      extraEnvironmentVariables: *videoExtraEnvVariables
      extraVolumeMounts: *videoExtraVolumeMounts
      extraVolumes:
        - name: video-data-pvclaim
          persistentVolumeClaim:
            claimName: selenium-edge-video-data-pvclaim
    startupProbe:
      httpGet:
        path: /status
        port: 5555
      failureThreshold: 120
      periodSeconds: 2
    terminationGracePeriodSeconds: 3600
    lifecycle:
      preStop:
        exec:
          command:
            - bash
            - -c
            - |
              curl -X POST 127.0.0.1:5555/se/grid/node/drain --header 'X-REGISTRATION-SECRET;' && \
              while curl 127.0.0.1:5555/status; do sleep 1; done

#jaeger-all-in-one:
  #enabled: true

ingress-nginx:
  #enabled: true
  controller:
    admissionWebhooks:
      enabled: false
    hostNetwork: true
    kind: DaemonSet
    service:
      type: ClusterIP
  tcp:
    4444: "{{ .Release.Namespace }}/selenium-router:4444"
    16686: "{{ .Release.Namespace }}/{{ .Release.Name }}-jaeger-all-in-one-headless:16686"

#keda:
  #enabled: true

grid-autoscaling:
  #enabled: true
  scale-chrome-node:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 20
    scaleTargetRef:
      name: selenium-chrome-node
    triggers:
      - type: selenium-grid
        metadata:
          browserName: 'chrome'
        authenticationRef:
          name: trigger-auth-grid-secret
  scale-firefox-node:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 20
    scaleTargetRef:
      name: selenium-firefox-node
    triggers:
      - type: selenium-grid
        metadata:
          browserName: 'firefox'
        authenticationRef:
          name: trigger-auth-grid-secret
  scale-edge-node:
    enabled: true
    minReplicaCount: 0
    maxReplicaCount: 20
    scaleTargetRef:
      name: selenium-edge-node
    triggers:
      - type: selenium-grid
        metadata:
          browserName: 'MicrosoftEdge'
        authenticationRef:
          name: trigger-auth-grid-secret
