tags:
  full: true
  selenium-grid: false
  jaeger-all-in-one: false
  ingress-nginx: false
  keda: false

global:
  seleniumGrid:
    persistence:
      enabled: true
    autoscaling:
      enableWithExistingKEDA: &enableWithExistingKEDA true
    videoImage: &videoImage "ndviet/video:ffmpeg-4.4.3-20231012"
  selenium-grid:
    #enabled: true
  jaeger-all-in-one:
    #enabled: true
  ingress-nginx:
    #enabled: true
  keda:
    #enabled: true

selenium-grid:
  #enabled: true
  basicAuth:
    enabled: false
  isolateComponents: true
  autoscaling:
    enableWithExistingKEDA: *enableWithExistingKEDA
    scalingType: job
    annotations:
      helm.sh/hook: post-install,post-upgrade,post-rollback
    deregisterLifecycle: {}
  components:
    extraEnvironmentVariables: &extraEnvironmentVariables
      - name: SE_NODE_MAX_SESSIONS
        value: "1"
      - name: SE_DRAIN_AFTER_SESSION_COUNT
        value: "1"
      - name: SE_ENABLE_TRACING
        value: "true"
      - name: JAVA_OPTS
        value: "-Dotel.traces.exporter=jaeger -Dotel.exporter.jaeger.endpoint=http://{{ .Release.Name }}-jaeger-all-in-one-headless:14250 -Dotel.resource.attributes=service.name=selenium"
      - name: SE_NODE_RECORD_VIDEO
        value: "true"

  chromeNode:
    extraEnvironmentVariables: *extraEnvironmentVariables
    ports: &nodePorts
      - 99
      - 5555
      - 5900
      - 7900
    sidecars: &nodeVideoRecord
      - name: video
        image: *videoImage
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DISPLAY_CONTAINER_NAME
            value: $(POD_IP)
          - name: FILE_NAME
            value: $(POD_IP)_$(POD_NAME).mp4
        volumeMounts:
          - name: videos
            mountPath: /videos
            subPathExpr: $(POD_NAME)
          - name: configurations
            mountPath: /etc/supervisord.conf
            subPath: supervisord.conf
    extraVolumes: &nodeVolumes
      - name: videos
        persistentVolumeClaim:
          claimName: "selenium-node-pvc"
      - name: configurations
        configMap:
          name: "selenium-configurations"
          defaultMode: 0511
    startupProbe: &nodeStartupProbe
      httpGet:
        path: /status
        port: 5555
      failureThreshold: 120
      periodSeconds: 2

  firefoxNode:
    extraEnvironmentVariables: *extraEnvironmentVariables
    ports: *nodePorts
    sidecars: *nodeVideoRecord
    extraVolumes: *nodeVolumes
    startupProbe: *nodeStartupProbe

  edgeNode:
    extraEnvironmentVariables: *extraEnvironmentVariables
    ports: *nodePorts
    sidecars: *nodeVideoRecord
    extraVolumes: *nodeVolumes
    startupProbe: *nodeStartupProbe

#jaeger-all-in-one:
  #enabled: true

ingress-nginx:
  #enabled: true
  controller:
    admissionWebhooks:
      enabled: false
    hostNetwork: true
    kind: DaemonSet
    service:
      type: ClusterIP
  tcp:
    4444: "{{ .Release.Namespace }}/selenium-router:4444"
    16686: "{{ .Release.Namespace }}/{{ .Release.Name }}-jaeger-all-in-one-headless:16686"

#keda:
  #enabled: true
